//
// Generated file, do not edit! Created by nedtool 5.1 from uavnet/routing/manet/base/ControlManetRouting.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __INET__INETMANET_CONTROLMANETROUTING_M_H
#define __INET__INETMANET_CONTROLMANETROUTING_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "inet/networklayer/common/L3Address.h"
// }}


namespace inet {
namespace inetmanet {

/**
 * Enum generated from <tt>uavnet/routing/manet/base/ControlManetRouting.msg:27</tt> by nedtool.
 * <pre>
 * enum ManetControlType
 * {
 * 
 *     MANET_ROUTE_NO_OPTION = 0;
 *     MANET_ROUTE_UPDATE = 1;
 *     MANET_ROUTE_NOROUTE = 2;
 * }
 * </pre>
 */
enum ManetControlType {
    MANET_ROUTE_NO_OPTION = 0,
    MANET_ROUTE_UPDATE = 1,
    MANET_ROUTE_NOROUTE = 2
};

/**
 * Class generated from <tt>uavnet/routing/manet/base/ControlManetRouting.msg:38</tt> by nedtool.
 * <pre>
 * //
 * // ICMP message class
 * //
 * packet ControlManetRouting
 * {
 *     L3Address srcAddress;
 *     L3Address destAddress;
 *     int optionCode \@enum(ManetControlType) = MANET_ROUTE_NO_OPTION;
 * }
 * </pre>
 */
class ControlManetRouting : public ::omnetpp::cPacket
{
  protected:
    L3Address srcAddress;
    L3Address destAddress;
    int optionCode;

  private:
    void copy(const ControlManetRouting& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ControlManetRouting&);

  public:
    ControlManetRouting(const char *name=nullptr, short kind=0);
    ControlManetRouting(const ControlManetRouting& other);
    virtual ~ControlManetRouting();
    ControlManetRouting& operator=(const ControlManetRouting& other);
    virtual ControlManetRouting *dup() const override {return new ControlManetRouting(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual L3Address& getSrcAddress();
    virtual const L3Address& getSrcAddress() const {return const_cast<ControlManetRouting*>(this)->getSrcAddress();}
    virtual void setSrcAddress(const L3Address& srcAddress);
    virtual L3Address& getDestAddress();
    virtual const L3Address& getDestAddress() const {return const_cast<ControlManetRouting*>(this)->getDestAddress();}
    virtual void setDestAddress(const L3Address& destAddress);
    virtual int getOptionCode() const;
    virtual void setOptionCode(int optionCode);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ControlManetRouting& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ControlManetRouting& obj) {obj.parsimUnpack(b);}

} // namespace inetmanet
} // namespace inet

#endif // ifndef __INET__INETMANET_CONTROLMANETROUTING_M_H

